language: node_js
node_js:
  - "10"

cache:
  directories:
    - "node_modules"

before_script:
  - "npm install -g polymer-cli"
  - "npm install"
script:
  - "polymer build --base-path warp10-photon"


deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: false
  local-dir: build/es6-bundled
  verbose: true
  on:
    branch: master
